# Generated by Django 3.2.3 on 2021-05-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturerequest',
            name='document',
            field=models.CharField(choices=[('통장사본', 2), ('주민등록등본', 1)], max_length=100),
        ),
    ]
