# Generated by Django 3.2.3 on 2021-05-30 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_picturerequest_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picturerequest',
            name='document',
            field=models.CharField(choices=[('주민등록등본', '주민등록등본'), ('통장사본', '통장사본'), ('가족관계증명서', '가족관계증명서'), ('신분증사본', '신분증사본')], max_length=100),
        ),
    ]
